#!/bin/sh
### BEGIN INIT INFO
# Provides:          @NAME@
# Required-Start:    $network $remote_fs
# Required-Stop:     $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: @DESC@
### END INIT INFO
#
# Written by `tiles service install`. SysV init has no per-user services, so
# this is a system service that drops to @USER@ before running.

NAME=@NAME@
USER=@USER@
BIN=@BIN@
ARGS=@COMMAND@
PIDFILE=/run/$NAME.pid
export TILES_CONFIG_DIR=@CONFIG@

case "$1" in
	start)
		start-stop-daemon --start --quiet --background --make-pidfile \
			--pidfile "$PIDFILE" --chuid "$USER" --exec "$BIN" -- $ARGS
		;;
	stop)
		start-stop-daemon --stop --quiet --pidfile "$PIDFILE" \
			--retry TERM/5/KILL/5
		rm -f "$PIDFILE"
		;;
	restart)
		"$0" stop
		"$0" start
		;;
	status)
		start-stop-daemon --status --pidfile "$PIDFILE"
		;;
	*)
		echo "usage: $0 {start|stop|restart|status}" >&2
		exit 2
		;;
esac
